title: 钱院学辅信息站 - qyxf.site
slogan: Info site of Qian Yuan Xue Fu!
organization_full: 西安交通大学钱学森书院学业辅导中心
version: 青云·雪峰 (V2.1)
plugins:
  - jekyll-mentions
  - jekyll-feed

markdown: kramdown
future: true
license_info: >
  如无特别声明，本站发布内容均采用<a href="https://creativecommons.org/licenses/by-sa/4.0/">知识共享 BY-SA 4.0
  协议</a>许可。使用者可在明确注明作者、作品链接之前提下转载本站作品，但必须使用相同或兼容的许可证对传播、再创作的内容授权。

# valine
valine:
  enable: true
  appid: PGiKOJ7cHFkr860I5ohCgSOn-gzGzoHsz
  appkey: SwTXHceYxOjiKMCIouFcB2ky
  notify: true
  verify: true
  placeholder: Write your comments
  avatar:
  guest_info: nickname, mail_address, website
  pageSize: 10

# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Qyxf
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software 
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum